WebApp/Controllers/BankAccountController.cs
using App.BLL.DTO;
using App.BLL.DTO.Identity;
using App.Contracts.BLL;
using Base.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Controllers;

public class BankAccountController : Controller
{
    private readonly IAppBll _bll;

    public BankAccountController(IAppBll bll)
    {
        _bll = bll;
    }

    // GET: Admin/BankAccount
    public async Task<IActionResult> Index()
    {
        var bankAccounts = await _bll.BankAccounts.GetAllAsync(User.GetUserId());
        return View(bankAccounts);
    }

    // GET: Admin/BankAccount/Details/5
    public async Task<IActionResult> Details(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var bankAccount = await _bll.BankAccounts.FirstOrDefaultAsync(id.Value, User.GetUserId());
        if (bankAccount == null)
        {
            return NotFound();
        }

        return View(bankAccount);
    }

    // GET: Admin/BankAccount/Create
    public async Task<IActionResult> Create()
    {
        ViewData["UserId"] = new SelectList(await _bll.Users.GetAllAsync(), nameof(AppUser.Id), nameof(AppUser.UserName));
        return View();
    }

    // POST: Admin/BankAccount/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(BankAccount bankAccount)
    {
        if (ModelState.IsValid)
        {
            bankAccount.Id = Guid.NewGuid();
            bankAccount.UserId = User.GetUserId();
            _bll.BankAccounts.Add(bankAccount);
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        ViewData["UserId"] = new SelectList(await _bll.Users.GetAllAsync(), nameof(AppUser.Id), nameof(AppUser.UserName), bankAccount.UserId);
        return View(bankAccount);
    }

    // GET: Admin/BankAccount/Edit/5
    public async Task<IActionResult> Edit(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var bankAccount = await _bll.BankAccounts.FirstOrDefaultAsync(id.Value, User.GetUserId());
        if (bankAccount == null)
        {
            return NotFound();
        }

        ViewData["UserId"] = new SelectList(await _bll.Users.GetAllAsync(), nameof(AppUser.Id), nameof(AppUser.UserName), bankAccount.UserId);
        return View(bankAccount);
    }

    // POST: Admin/BankAccount/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, BankAccount bankAccount)
    {
        if (id != bankAccount.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                await _bll.BankAccounts.UpdateAsync(bankAccount, User.GetUserId());
                await _bll.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await BankAccountExists(bankAccount.Id))
                {
                    return NotFound();
                }

                throw;
            }

            return RedirectToAction(nameof(Index));
        }

        ViewData["UserId"] = new SelectList(await _bll.Users.GetAllAsync(), nameof(AppUser.Id), nameof(AppUser.UserName), bankAccount.UserId);
        return View(bankAccount);
    }

    // GET: Admin/BankAccount/Delete/5
    public async Task<IActionResult> Delete(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var bankAccount = await _bll.BankAccounts.FirstOrDefaultAsync(id.Value, User.GetUserId());
        if (bankAccount == null)
        {
            return NotFound();
        }

        return View(bankAccount);
    }

    // POST: Admin/BankAccount/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
            
        await _bll.BankAccounts.RemoveAsync(id, User.GetUserId());
        await _bll.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private async Task<bool> BankAccountExists(Guid id)
    {
        return await _bll.BankAccounts.ExistsAsync(id);
    }
}

WebApp/Controllers/EventController.cs
using App.BLL.DTO;
using App.Contracts.BLL;
using Base.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Controllers;

public class EventController : Controller
{
    private readonly IAppBll _bll;

    public EventController(IAppBll bll)
    {
        _bll = bll;
    }

    // GET: Admin/Event
    public async Task<IActionResult> Index()
    {
        var meetingEvents = await _bll.Events.GetAllAsync(User.GetUserId());
        return View(meetingEvents);
    }

    // GET: Admin/Event/Details/5
    public async Task<IActionResult> Details(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var dbEvent = await _bll.Events.FirstOrDefaultAsync(id.Value, User.GetUserId());
        if (dbEvent == null)
        {
            return NotFound();
        }

        return View(dbEvent);
    }

    // GET: Admin/Event/Create
    public async Task<IActionResult> Create()
    {
        ViewData["MeetingId"] = new SelectList(await _bll.Meetings.GetAllAsync(User.GetUserId()), nameof(Meeting.Id), nameof(Meeting.Title));
        return View();
    }

    // POST: Admin/Event/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Event newEvent)
    {
        if (ModelState.IsValid)
        {
            newEvent.Id = Guid.NewGuid();
            _bll.Events.Add(newEvent);
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        ViewData["MeetingId"] = new SelectList(await _bll.Meetings.GetAllAsync(User.GetUserId()), nameof(Meeting.Id), nameof(Meeting.Title), newEvent.MeetingId);
        return View(newEvent);
    }

    // GET: Admin/Event/Edit/5
    public async Task<IActionResult> Edit(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var dbEvent = await _bll.Events.FirstOrDefaultAsync(id.Value, User.GetUserId());
        if (dbEvent == null)
        {
            return NotFound();
        }

        ViewData["MeetingId"] = new SelectList(await _bll.Meetings.GetAllAsync(User.GetUserId()), nameof(Meeting.Id), nameof(Meeting.Title), dbEvent.MeetingId);
        return View(dbEvent);
    }

    // POST: Admin/Event/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, Event editEvent)
    {
        if (id != editEvent.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                await _bll.Events.UpdateAsync(editEvent);
                await _bll.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await EventExists(editEvent.Id))
                {
                    return NotFound();
                }

                throw;
            }

            return RedirectToAction(nameof(Index));
        }

        ViewData["MeetingId"] = new SelectList(await _bll.Meetings.GetAllAsync(User.GetUserId()), nameof(Meeting.Id), nameof(Meeting.Title), editEvent.MeetingId);
        return View(editEvent);
    }

    // GET: Admin/Event/Delete/5
    public async Task<IActionResult> Delete(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var dbEvent = await _bll.Events.FirstOrDefaultAsync(id.Value, User.GetUserId());
        if (dbEvent == null)
        {
            return NotFound();
        }

        return View(dbEvent);
    }

    // POST: Admin/Event/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
            
        await _bll.Events.RemoveAsync(id, User.GetUserId());
        await _bll.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private async Task<bool> EventExists(Guid id)
    {
        return await _bll.Events.ExistsAsync(id);
    }
}

WebApp/Controllers/MeetingController.cs
using App.BLL.DTO;
using App.Contracts.BLL;
using Base.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Controllers;

public class MeetingController : Controller
{
    private readonly IAppBll _bll;

    public MeetingController(IAppBll bll)
    {
        _bll = bll;
    }

    // GET: Admin/Meeting
    public async Task<IActionResult> Index()
    {
        return View(await _bll.Meetings.GetAllAsync(User.GetUserId()));
    }

    // GET: Admin/Meeting/Details/5
    public async Task<IActionResult> Details(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var meeting = await _bll.Meetings.FirstOrDefaultAsync(id.Value, User.GetUserId());
        if (meeting == null)
        {
            return NotFound();
        }

        return View(meeting);
    }

    // GET: Admin/Meeting/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Admin/Meeting/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Meeting meeting)
    {
        if (ModelState.IsValid)
        {
            meeting.Id = Guid.NewGuid();
            _bll.Meetings.Add(meeting);
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        return View(meeting);
    }

    // GET: Admin/Meeting/Edit/5
    public async Task<IActionResult> Edit(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var meeting = await _bll.Meetings.FirstOrDefaultAsync(id.Value, User.GetUserId());
        if (meeting == null)
        {
            return NotFound();
        }

        return View(meeting);
    }

    // POST: Admin/Meeting/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, Meeting meeting)
    {
        if (id != meeting.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                await _bll.Meetings.UpdateAsync(meeting);
                await _bll.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await MeetingExists(meeting.Id))
                {
                    return NotFound();
                }

                throw;
            }

            return RedirectToAction(nameof(Index));
        }

        return View(meeting);
    }

    // GET: Admin/Meeting/Delete/5
    public async Task<IActionResult> Delete(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var meeting = await _bll.Meetings.FirstOrDefaultAsync(id.Value, User.GetUserId());
        if (meeting == null)
        {
            return NotFound();
        }

        return View(meeting);
    }

    // POST: Admin/Meeting/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
        await _bll.Meetings.RemoveAsync(id, User.GetUserId());
        await _bll.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private async Task<bool> MeetingExists(Guid id)
    {
        return await _bll.Meetings.ExistsAsync(id);
    }
}

WebApp/Controllers/PaymentController.cs
using App.BLL.DTO;
using App.BLL.DTO.Identity;
using App.Contracts.BLL;
using Base.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Controllers;

public class PaymentController : Controller
{
    private readonly IAppBll _bll;

    public PaymentController(IAppBll bll)
    {
        _bll = bll;
    }

    // GET: Admin/Payment
    public async Task<IActionResult> Index()
    {
        var payments = await _bll.Payments.GetAllAsync(User.GetUserId());
        return View(payments);
    }

    // GET: Admin/Payment/Details/5
    public async Task<IActionResult> Details(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var payment = await _bll.Payments.FirstOrDefaultAsync(id.Value, User.GetUserId());
        if (payment == null)
        {
            return NotFound();
        }

        return View(payment);
    }

    // GET: Admin/Payment/Create
    public async Task<IActionResult> Create()
    {
        ViewData["RequirementId"] = new SelectList(await _bll.Requirements.GetAllAsync(User.GetUserId()), nameof(Requirement.Id), nameof(Requirement.Title));
        ViewData["UserId"] = new SelectList(await _bll.Users.GetAllAsync(), nameof(AppUser.Id), nameof(AppUser.UserName));
        return View();
    }

    // POST: Admin/Payment/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Payment payment)
    {
        if (ModelState.IsValid)
        {
            payment.Id = Guid.NewGuid();
            payment.UserId = User.GetUserId();
            _bll.Payments.Add(payment);
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        ViewData["RequirementId"] = new SelectList(await _bll.Requirements.GetAllAsync(User.GetUserId()), nameof(Requirement.Id), nameof(Requirement.Title), payment.RequirementId);
        ViewData["UserId"] = new SelectList(await _bll.Users.GetAllAsync(), nameof(AppUser.Id), nameof(AppUser.UserName), payment.UserId);
        return View(payment);
    }

    // GET: Admin/Payment/Edit/5
    public async Task<IActionResult> Edit(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var payment = await _bll.Payments.FirstOrDefaultAsync(id.Value, User.GetUserId());
        if (payment == null)
        {
            return NotFound();
        }

        ViewData["RequirementId"] = new SelectList(await _bll.Requirements.GetAllAsync(User.GetUserId()), nameof(Requirement.Id), nameof(Requirement.Title), payment.RequirementId);
        ViewData["UserId"] = new SelectList(await _bll.Users.GetAllAsync(), nameof(AppUser.Id), nameof(AppUser.UserName), payment.UserId);
        return View(payment);
    }

    // POST: Admin/Payment/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, Payment payment)
    {
        if (id != payment.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                await _bll.Payments.UpdateAsync(payment, User.GetUserId());
                await _bll.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await PaymentExists(payment.Id))
                {
                    return NotFound();
                }

                throw;
            }

            return RedirectToAction(nameof(Index));
        }

        ViewData["RequirementId"] = new SelectList(await _bll.Requirements.GetAllAsync(User.GetUserId()), nameof(Requirement.Id), nameof(Requirement.Title), payment.RequirementId);
        ViewData["UserId"] = new SelectList(await _bll.Users.GetAllAsync(), nameof(AppUser.Id), nameof(AppUser.UserName), payment.UserId);
        return View(payment);
    }

    // GET: Admin/Payment/Delete/5
    public async Task<IActionResult> Delete(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var payment = await _bll.Payments.FirstOrDefaultAsync(id.Value, User.GetUserId());
        if (payment == null)
        {
            return NotFound();
        }

        return View(payment);
    }

    // POST: Admin/Payment/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
        await _bll.Payments.RemoveAsync(id, User.GetUserId());
        await _bll.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private async Task<bool> PaymentExists(Guid id)
    {
        return await _bll.Payments.ExistsAsync(id);
    }
}

WebApp/Pages/Shared/_LanguageSelector.cshtml
@using Microsoft.Extensions.Options
@inject IOptions<RequestLocalizationOptions> _localizationOptions

@{
    var cultureItems = _localizationOptions.Value.SupportedCultures!
        .Select(c => new {Value = c.Name, Text = c.NativeName}).ToList();
}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="javascript:{}" id="navbarLangDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@Base.Resources.Common.Language</a>
    <div class="dropdown-menu" aria-labelledby="navbarLangDropdown">
        @foreach (var item in cultureItems)
        {
            <a class="dropdown-item @(Thread.CurrentThread.CurrentUICulture.Name == item.Value ? "active" : "")"
               asp-area="" asp-controller="Home" asp-action="SetLanguage" asp-route-culture="@item.Value"
               asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString">
                @item.Text
            </a>
        }
    </div>
</li>

WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">WebApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarLangDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Controllers</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Event" asp-action="Index">Event</a>
                    </l1>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="EventNavigation" asp-action="Index">EventNavigation</a>
                    </l1>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="EventUser" asp-action="Index">EventUser</a>
                    </l1>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Meeting" asp-action="Index">Meeting</a>
                    </l1>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="MeetingUser" asp-action="Index">MeetingUser</a>
                    </l1>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="BankAccount" asp-action="Index">BankAccount</a>
                    </l1>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="MoneyTransfer" asp-action="Index">MoneyTransfer</a>
                    </l1>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Payment" asp-action="Index">Payment</a>
                    </l1>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Questionnaire" asp-action="Index">Questionnaire</a>
                    </l1>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="QuestionnaireRelation" asp-action="Index">QuestionnaireRelation</a>
                    </l1>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="AnswerOption" asp-action="Index">AnswerOption</a>
                    </l1>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Requirement" asp-action="Index">Requirement</a>
                    </l1>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="RequirementOption" asp-action="Index">RequirementOption</a>
                    </l1>
                    <l1 class="nav-item">
                        <a class="nav-link text-dark" asp-controller="RequirementUser" asp-action="Index">RequirementUser</a>
                    </l1>
                </ul>
            </div>

            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>
                    
                    <li>
                        <div style="height: 100%; width: 2.5px; background: #777; border-radius: 5px;"></div>
                    </li>
                    
                    <partial name="_LanguageSelector"/>
                    
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - WebApp | UI Culture: @Thread.CurrentThread.CurrentUICulture.Name | Culture: @Thread.CurrentThread.CurrentCulture.Name
        <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>